FROM node:18-alpine as build

ARG env
ENV env $env

ARG GENERATE_SOURCEMAP
ENV GENERATE_SOURCEMAP $GENERATE_SOURCEMAP

ARG CI
ENV CI $CI

ARG PRERENDER
ENV PRERENDER $PRERENDER

ARG NEXT_PUBLIC_OSM_PROVIDER_HOST
ENV NEXT_PUBLIC_OSM_PROVIDER_HOST $NEXT_PUBLIC_OSM_PROVIDER_HOST

ARG NEXT_PUBLIC_OSM_PROVIDER_URL
ENV NEXT_PUBLIC_OSM_PROVIDER_URL $NEXT_PUBLIC_OSM_PROVIDER_URL

ARG NEXT_PUBLIC_OSM_PROVIDER_URL_DARK
ENV NEXT_PUBLIC_OSM_PROVIDER_URL_DARK $NEXT_PUBLIC_OSM_PROVIDER_URL_DARK

ARG NEXT_PUBLIC_CI_JOB_ID
ENV NEXT_PUBLIC_CI_JOB_ID $NEXT_PUBLIC_CI_JOB_ID

ARG NEXT_COMMIT_HASH
ENV NEXT_COMMIT_HASH $NEXT_COMMIT_HASH

ARG NEXT_COMMIT_MESSAGE
ENV NEXT_COMMIT_MESSAGE $NEXT_COMMIT_MESSAGE

ARG NEXT_COMMIT_VERSION
ENV NEXT_COMMIT_VERSION $NEXT_COMMIT_VERSION

ARG NEXT_REPO_URL
ENV NEXT_REPO_URL $NEXT_REPO_URL

WORKDIR /usr/src/app

COPY . ./

RUN yarn install && yarn build

FROM nginx:1.23.1-alpine
COPY --from=build /usr/src/app/out /usr/share/nginx/html
